### ISSUE TITLE
[线程安全]LazySingleton.instance()有可能返回null?

### ISSUE THREAD

**Issue by jimmy384** [cosycode/common-lang#1]
https://github.com/cosycode/common-lang/blob/c9f537723d5a7e9da3b682c65ba924a0aff24f7d/src/main/java/com/github/cosycode/common/ext/hub/LazySingleton.java#L43

instance()离开synchronized后，destory有可能进入synchronized把引用t设成null，instance()有可能返回null？

**Comment by cpfree** [comment]
是的, 你说得对, destroy()是我下意识加的一个, 看来似乎引起了一个bug, 而且destory似乎没有必要, 如果想要新建单例的话,就直接重新建立LazySingeton对象就好了, 
多谢指点, 下个版本就把它@Deprecated掉!

**Comment by cpfree** [comment]
[LazySingleton.java](https://github.com/cosycode/common-lang/blob/b97cffc03a0bc57da23190c7c2dcc700e6a94ac9/src/main/java/com/github/cosycode/common/ext/hub/LazySingleton.java)
已经修复了, 这样的话, 就不会返回null了吧😀

    /**
     * 双重锁单例
     *
     * @return 值
     */
    public T instance() {
        T tmp = t;
        if (tmp == null) {
            synchronized (this) {
                if (t == null) {
                    t = supplier.get();
                }
                tmp = t;
            }
        }
        return tmp;
    }
